### ISSUE TITLE
pom.xml 好像少了lib？ibatis？

### ISSUE THREAD

**Issue by 82kg** [wander-chu/SpringBoot-Blog#1]
增加依赖

        <dependency>
            <groupId>org.apache.ibatis</groupId>
            <artifactId>ibatis-core</artifactId>
            <version>3.0</version>
        </dependency>

启动项目后报错：
Description:

An attempt was made to call the method org.apache.ibatis.session.Configuration.setVfsImpl(Ljava/lang/Class;)V but it does not exist. Its class, org.apache.ibatis.session.Configuration, is available from the following locations:

    jar:file:/D:/work/maven/repository/org/apache/ibatis/ibatis-core/3.0/ibatis-core-3.0.jar!/org/apache/ibatis/session/Configuration.class

It was loaded from the following location:

    file:/D:/work/maven/repository/org/apache/ibatis/ibatis-core/3.0/ibatis-core-3.0.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.apache.ibatis.session.Configuration

**Comment by wander-chu** [comment]
用的是MyBatis，pom.xml里面已经有相关依赖了：
```
<dependency>
        <groupId>org.mybatis.spring.boot</groupId>
        <artifactId>mybatis-spring-boot-starter</artifactId>
        <version>2.0.0</version>
</dependency>
```
这个项目可以直接运行，不用自己再添加依赖。
